services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_gui
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:

